from domain.use_cases.create_failure import CreateFailureUseCase
